# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region  = "us-west-2"
  profile = "chapter"

  default_tags {
    tags = {
      Project = "chapter"
      Owner   = "denis.galkin.91@gmail.com"
    }
  }
}
