# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "chapter-terraform-state-usw2"
    encrypt = true
    key     = "global-preferences/iam/terraform.tfstate"
    profile = "chapter"
    region  = "us-west-2"
  }
}
