# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "chapter-2-terraform-state-euc1"
    encrypt = true
    key     = "shared/iam/terraform.tfstate"
    profile = "chapter-web-2"
    region  = "eu-central-1"
  }
}
