# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region  = "eu-central-1"
  profile = "chapter-web-2"

  default_tags {
    tags = {
      Project = "chapter"
      Owner   = "denis.galkin.91@gmail.com"
    }
  }
}
