# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = "= 1.5.6"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.9"
    }
  }
}
