name: labeler
on: 
  pull_request_target:
    types: [opened]
  pull_request:
    branches: [ "main" ]
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - name: Check Labels
      id: labeler
      uses: jimschubert/labeler-action@v2
      with:
        GITHUB_TOKEN: ${{ github.token }}
