name: labeler
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  labeler:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Check Labels
      id: labeler
      uses: jimschubert/labeler-action@v2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
