name: tf-infra-test

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  tflint:
     uses: ./.github/workflows/tflint.yml
  tfsec:
     uses: ./.github/workflows/tfsec.yml
     permissions:
       actions: read
       contents: read
       security-events: write
  tftest:
     uses: ./.github/workflows/tftest.yml
