name: tfsec

on:
  workflow_call:

jobs:
  tfsec:
    name: Run tfsec
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Run tfsec sarif
        uses: aquasecurity/tfsec-sarif-action@v0.1.4
        if: ${{ github.ref_name == 'main' }}
        with:
          sarif_file: tfsec.sarif
          full_repo_scan: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2.21.7
        if: ${{ github.ref_name == 'main' }}
        with:
          sarif_file: tfsec.sarif

      - name: Comment PR
        uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
        if: ${{ github.event_name == 'pull_request' }}
        with:
          github_token: ${{ github.token }}
          soft_fail_commenter: false
